### ISSUE TITLE
"Wrong password for username ..."

### ISSUE THREAD

**Issue by seanlynch** [damko/freedommarks-browser-webextension#4]
With NextCloud 12 and Firefox 55.0.2, just keeps giving "Wrong password for username" followed by my username. I'm using an app password, but the Passman extension is working fine. I've tried two separate app passwords and the URL with and without the / at the end. Using https with a LetsEncrypt certificate.

**Comment by shtrom** [comment]
Exactly the same issue here: app password (and U2F 2FA), and HTTPS/letsencrypt. Not using Passman, though, but everything else using an app password works well.

**Comment by shtrom** [comment]
The OCBookmarks https://github.com/theScrabi/OCBookmarks Android app also seems to use HTTP Auth with the app password (against the `v2` API).

```
cloud.example.net 110.175.91.66 - shtrom [20/Dec/2017:05:16:15 +0100] "GET /index.php/apps/bookmarks/public/rest/v2/bookmark?page=-1 HTTP/1.1" 200 419728 "-" "Dalvik/2.1.0 (Linux; U; Android 7.1.2; Nexus 5 Build/NJH47F)"
```

**Comment by damko** [comment]
There were some issue in the recent past with the API on server side mostly due to many many changes in the codebase. 
You've probably already noticed this but since a couple of months these issues are solved.
Currently FreedomMarks 0.0.7 works quite well with NextCloud 12.0.4

**Comment by shtrom** [comment]
Ah! Nice! Thanks for that!

**Comment by seanlynch** [comment]
Unfortunately the version in the Chrome store is still 0.0.2. Are you planning on uploading a new build?
